// js/i18n.js
const translations = {
  en: { shop:"Shop", new:"New Arrivals", dresses:"Dresses", tops:"Tops", accessories:"Accessories", sale:"Sale", about:"About", hoodies:"HOODIES", cargo:"CARGO", tees:"TEES", heroTitle:"NEW<br>DROP", heroDesc:"Curated looks. Tap to shop the full fit.", shopBtn:"SHOP NOW", pi:"Personal Information", orders:"Order History", loginSec:"Login & Security", signin:"Sign In", signup:"Sign Up", signout:"Sign Out", firstName:"First Name", lastName:"Last Name", street:"Street Name", city:"City", country:"Country", postcode:"Postcode", phone:"Phone Number", email:"Email", save:"SAVE CHANGES", upload:"Upload Photo" },
  tr: { shop:"Mağaza", new:"Yeni Gelenler", dresses:"Elbiseler", tops:"Üstler", accessories:"Aksesuarlar", sale:"İndirim", about:"Hakkımızda", hoodies:"KAPÜŞONLU", cargo:"KARGO", tees:"TİŞÖRT", heroTitle:"YENİ<br>SEZON", heroDesc:"Özenle seçilmiş kombinler.", shopBtn:"ALIŞVERİŞ YAP", pi:"Kişisel Bilgiler", orders:"Sipariş Geçmişi", loginSec:"Giriş ve Güvenlik", signin:"Giriş Yap", signup:"Kayıt Ol", signout:"Çıkış Yap", firstName:"Ad", lastName:"Soyad", street:"Sokak Adı", city:"Şehir", country:"Ülke", postcode:"Posta Kodu", phone:"Telefon", email:"E-posta", save:"KAYDET", upload:"Fotoğraf Yükle" },
  de: { shop:"Shop", new:"Neuheiten", dresses:"Kleider", tops:"Tops", accessories:"Accessoires", sale:"Sale", about:"Über uns", hoodies:"HOODIES", cargo:"CARGO", tees:"T-SHIRTS", heroTitle:"NEUE<br>KOLLEKTION", heroDesc:"Kuratierte Looks.", shopBtn:"JETZT KAUFEN", pi:"Persönliche Daten", orders:"Bestellverlauf", loginSec:"Login & Sicherheit", signin:"Anmelden", signup:"Registrieren", signout:"Abmelden", firstName:"Vorname", lastName:"Nachname", street:"Straße", city:"Stadt", country:"Land", postcode:"PLZ", phone:"Telefon", email:"E-Mail", save:"SPEICHERN", upload:"Foto hochladen" },
  fr: { shop:"Boutique", new:"Nouveautés", dresses:"Robes", tops:"Hauts", accessories:"Accessoires", sale:"Soldes", about:"À propos", hoodies:"HOODIES", cargo:"CARGO", tees:"T-SHIRTS", heroTitle:"NOUVELLE<br>COLLECTION", heroDesc:"Looks sélectionnés.", shopBtn:"ACHETER", pi:"Informations Personnelles", orders:"Historique des commandes", loginSec:"Connexion et sécurité", signin:"Se Connecter", signup:"S'inscrire", signout:"Déconnexion", firstName:"Prénom", lastName:"Nom", street:"Rue", city:"Ville", country:"Pays", postcode:"Code Postal", phone:"Téléphone", email:"E-mail", save:"ENREGISTRER", upload:"Photo" },
  es: { shop:"Tienda", new:"Novedades", dresses:"Vestidos", tops:"Tops", accessories:"Accesorios", sale:"Ofertas", about:"Sobre", hoodies:"SUDADERAS", cargo:"CARGO", tees:"CAMISETAS", heroTitle:"NUEVA<br>COLECCIÓN", heroDesc:"Looks seleccionados.", shopBtn:"COMPRAR", pi:"Información Personal", orders:"Historial de pedidos", loginSec:"Inicio de sesión y seguridad", signin:"Iniciar Sesión", signup:"Registrarse", signout:"Cerrar Sesión", firstName:"Nombre", lastName:"Apellido", street:"Calle", city:"Ciudad", country:"País", postcode:"Código Postal", phone:"Teléfono", email:"Correo", save:"GUARDAR", upload:"Subir Foto" },
  it: { shop:"Negozio", new:"Novità", dresses:"Vestiti", tops:"Top", accessories:"Accessori", sale:"Saldi", about:"Chi Siamo", hoodies:"FELPE", cargo:"CARGO", tees:"T-SHIRT", heroTitle:"NUOVA<br>COLLEZIONE", heroDesc:"Look curati.", shopBtn:"ACQUISTA", pi:"Informazioni Personali", orders:"Cronologia ordini", loginSec:"Accesso e sicurezza", signin:"Accedi", signup:"Registrati", signout:"Esci", firstName:"Nome", lastName:"Cognome", street:"Via", city:"Città", country:"Paese", postcode:"CAP", phone:"Telefono", email:"Email", save:"SALVA", upload:"Carica Foto" },
  nl: { shop:"Winkel", new:"Nieuw", dresses:"Jurken", tops:"Tops", accessories:"Accessoires", sale:"Sale", about:"Over Ons", hoodies:"HOODIES", cargo:"CARGO", tees:"T-SHIRTS", heroTitle:"NIEUWE<br>DROP", heroDesc:"Gecureerde looks.", shopBtn:"SHOP NU", pi:"Persoonlijke Info", orders:"Bestelgeschiedenis", loginSec:"Inloggen en beveiliging", signin:"Inloggen", signup:"Registreren", signout:"Uitloggen", firstName:"Voornaam", lastName:"Achternaam", street:"Straat", city:"Stad", country:"Land", postcode:"Postcode", phone:"Telefoon", email:"E-mail", save:"OPSLAAN", upload:"Foto Uploaden" },
  el: { shop:"Κατάστημα", new:"Νέες Αφίξεις", dresses:"Φορέματα", tops:"Τοπ", accessories:"Αξεσουάρ", sale:"Εκπτώσεις", about:"Σχετικά", hoodies:"ΦΟΥΤΕΡ", cargo:"CARGO", tees:"ΜΠΛΟΥΖΑΚΙΑ", heroTitle:"ΝΕΑ<br>ΣΥΛΛΟΓΗ", heroDesc:"Επιμελημένα looks.", shopBtn:"ΑΓΟΡΑΣΕ ΤΩΡΑ", pi:"Προσωπικές Πληροφορίες", orders:"Ιστορικό παραγγελιών", loginSec:"Σύνδεση και ασφάλεια", signin:"Σύνδεση", signup:"Εγγραφή", signout:"Αποσύνδεση", firstName:"Όνομα", lastName:"Επώνυμο", street:"Οδός", city:"Πόλη", country:"Χώρα", postcode:"ΤΚ", phone:"Τηλέφωνο", email:"Email", save:"ΑΠΟΘΗΚΕΥΣΗ", upload:"Ανέβασμα Φωτογραφίας" },
  pl: { shop:"Sklep", new:"Nowości", dresses:"Sukienki", tops:"Topy", accessories:"Akcesoria", sale:"Wyprzedaż", about:"O nas", hoodies:"BLUZY", cargo:"CARGO", tees:"T-SHIRTY", heroTitle:"NOWA<br>KOLEKCJA", heroDesc:"Wybrane stylizacje.", shopBtn:"KUP TERAZ", pi:"Dane Osobowe", orders:"Historia zamówień", loginSec:"Logowanie i bezpieczeństwo", signin:"Zaloguj", signup:"Zarejestruj", signout:"Wyloguj", firstName:"Imię", lastName:"Nazwisko", street:"Ulica", city:"Miasto", country:"Kraj", postcode:"Kod", phone:"Telefon", email:"Email", save:"ZAPISZ", upload:"Prześlij Zdjęcie" },
  pt: { shop:"Loja", new:"Novidades", dresses:"Vestidos", tops:"Tops", accessories:"Acessórios", sale:"Promoções", about:"Sobre", hoodies:"MOLETONS", cargo:"CARGO", tees:"CAMISETAS", heroTitle:"NOVA<br>COLEÇÃO", heroDesc:"Looks selecionados.", shopBtn:"COMPRAR AGORA", pi:"Informação Pessoal", orders:"Histórico de pedidos", loginSec:"Login e segurança", signin:"Entrar", signup:"Registrar", signout:"Sair", firstName:"Nome", lastName:"Sobrenome", street:"Rua", city:"Cidade", country:"País", postcode:"Código Postal", phone:"Telefone", email:"Email", save:"SALVAR", upload:"Carregar Foto" },
  id: { shop:"Toko", new:"Baru", dresses:"Gaun", tops:"Atasan", accessories:"Aksesori", sale:"Obral", about:"Tentang", hoodies:"HOODIE", cargo:"KARGO", tees:"KAOS", heroTitle:"KOLEKSI<br>BARU", heroDesc:"Tampilan pilihan.", shopBtn:"BELANJA", pi:"Informasi Pribadi", orders:"Riwayat Pesanan", loginSec:"Login & Keamanan", signin:"Masuk", signup:"Daftar", signout:"Keluar", firstName:"Nama Depan", lastName:"Nama Belakang", street:"Jalan", city:"Kota", country:"Negara", postcode:"Kode Pos", phone:"Telepon", email:"Email", save:"SIMPAN", upload:"Unggah Foto" },
  zh: { shop:"商店", new:"新品", dresses:"连衣裙", tops:"上衣", accessories:"配饰", sale:"特卖", about:"关于", hoodies:"连帽衫", cargo:"工装裤", tees:"T恤", heroTitle:"全新<br>系列", heroDesc:"精选穿搭。", shopBtn:"立即购买", pi:"个人信息", orders:"订单历史", loginSec:"登录与安全", signin:"登录", signup:"注册", signout:"退出", firstName:"名", lastName:"姓", street:"街道", city:"城市", country:"国家", postcode:"邮编", phone:"电话", email:"邮箱", save:"保存", upload:"上传照片" }
};

function applyLanguage(lang){
  const t = translations[lang] || translations.en;
  document.querySelectorAll('[data-i18n]').forEach(el=>{
    const key = el.getAttribute('data-i18n');
    if(t[key]){
      if(key==='heroTitle') el.innerHTML=t[key];
      else el.textContent=t[key];
    }
  });
  localStorage.setItem('lang', lang);
  document.documentElement.lang=lang;
}

document.addEventListener('DOMContentLoaded', ()=>{
  const langSel=document.getElementById('language');
  if(!langSel) return;
  const savedLang=localStorage.getItem('lang')||'en';
  langSel.value=savedLang;
  applyLanguage(savedLang);
  langSel.addEventListener('change', e=> applyLanguage(e.target.value));
});
